/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface ParentComponent {
    }
    interface SlotComponent {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {
    }
    var HTMLParentComponentElement: {
        prototype: HTMLParentComponentElement;
        new (): HTMLParentComponentElement;
    };
    interface HTMLSlotComponentElement extends Components.SlotComponent, HTMLStencilElement {
    }
    var HTMLSlotComponentElement: {
        prototype: HTMLSlotComponentElement;
        new (): HTMLSlotComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "parent-component": HTMLParentComponentElement;
        "slot-component": HTMLSlotComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface ParentComponent {
    }
    interface SlotComponent {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "parent-component": ParentComponent;
        "slot-component": SlotComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "parent-component": LocalJSX.ParentComponent & JSXBase.HTMLAttributes<HTMLParentComponentElement>;
            "slot-component": LocalJSX.SlotComponent & JSXBase.HTMLAttributes<HTMLSlotComponentElement>;
        }
    }
}
